name: ci
on: [push, pull_request]
jobs:
  image:
    name: "Publish kubectl image on Docker Hub"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        kubectl:
          - v1.34.0

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set Docker tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo DOCKER_TAGS=tsuru/kubectl:${{ matrix.kubectl }},tsuru/kubectl:${{ matrix.kubectl }}-${GITHUB_REF##*/} >> $GITHUB_ENV
          else
            echo DOCKER_TAGS=tsuru/kubectl:${{ matrix.kubectl }}-${GITHUB_REF##*/} >> $GITHUB_ENV
          fi
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
          build-args: |
            KUBECTL_RELEASE=${{ matrix.kubectl }}
